/* INPUT DATASET */
PROC IMPORT DATAFILE= "F:\wbc.csv"
  OUT=wbc 
  DBMS=CSV REPLACE;
  GETNAMES=YES;    
RUN;

/* LOG VARIABLE */
DATA wbc1;
  SET wbc;
  logwbc=log(wbc_engraft);
RUN;

/* SUMMARIZE VARIABLES*/
PROC MEANS DATA=wbc1 MEAN MEDIAN MIN MAX RANGE VAR STD;
  VAR wbc_engraft logwbc;
RUN;

/* MACRO FOR SAMPLE SIZE CALCULATION */
%MACRO SAMPLESIZE(n,d);
PROC POWER;
  ONESAMPLEMEANS TEST=t
  SIDES=&n
  MEAN=&d
  STDDEV=0.1240
  ALPHA=0.05
  NTOTAL=.
  POWER=0.8;
RUN;
%MEND;

/* CALCULATE SAMPLE SIZE */
%SAMPLESIZE(1,0.1625);
%SAMPLESIZE(2,0.1625);
%SAMPLESIZE(1,0.2231);
%SAMPLESIZE(2,0.2231);
%SAMPLESIZE(1,0.2876);
%SAMPLESIZE(2,0.2876);
