#beta distribution graph
theta=seq(from=0,to=1,length.out=100)
y1=dbeta(theta,3,3)
y2=dbeta(theta,2,3)
y3=dbeta(theta,3,2)
plot(theta,y1,type='l',ylab='Density',xlab=expression(pi))
lines(theta,y2,type="l",col="red")
lines(theta,y3,type="l",col="blue")
legend("topright",c("a=3 b=3","a=2 b=3","a=3 b=2"),text.col=c("black","red","blue"))

#binomial distribution graph
theta=seq(from=0,to=20,by=1)
y1=dbinom(theta,20,0.25)
y2=dbinom(theta,20,0.5)
y3=dbinom(theta,20,0.75)
plot(theta,y1,type='h',ylab='Density',xlab=expression(pi))
lines(theta,y2,type="h",col="red")
lines(theta,y3,type="h",col="blue")
legend("topright",c("n=20 p=0.25","n=20 p=0.5","n=20 p=0.75"),text.col=c("black","red","blue"))

#poisson distribution graph
theta=seq(from=0,to=20,by=1)
y1=dpois(theta,5)
y2=dpois(theta,10)
y3=dpois(theta,15)
plot(theta,y1,type='h',ylab='Density',xlab=expression(pi))
lines(theta,y2,type="h",col="red")
lines(theta,y3,type="h",col="blue")
legend("topright",c("lambda=5","lambda=10","lambda=15"),text.col=c("black","red","blue"))

#gamma distribution graph
theta=seq(from=0,to=50,by=1)
y1=dgamma(theta,1,1)
y2=dgamma(theta,5,1)
y3=dgamma(theta,25,1)
plot(theta,y1,type='l',ylab='Density',xlab=expression(pi))
lines(theta,y2,type="l",col="red")
lines(theta,y3,type="l",col="blue")
legend("topright",c("a=1 b=1","a=5 b=1","a=25 b=1"),text.col=c("black","red","blue"))
y4=dgamma(theta,25,1)
y5=dgamma(theta,25,2)
y6=dgamma(theta,25,3)
plot(theta,y4,type='l',ylab='Density',xlab=expression(pi))
lines(theta,y5,type="l",col="red")
lines(theta,y6,type="l",col="blue")
legend("topright",c("a=25 b=1","a=25 b=2","a=25 b=3"),text.col=c("black","red","blue"))

#normal distribution graph
theta=seq(from=-10,to=10,length.out=100)
y1=dnorm(theta,-5,1)
y2=dnorm(theta,0,1)
y3=dnorm(theta,5,1)
plot(theta,y1,type='l',ylab='Density',xlab=expression(pi))
lines(theta,y2,type="l",col="red")
lines(theta,y3,type="l",col="blue")
legend("topright",c("a=-5 b=1","a=0 b=1","a=5 b=1"),text.col=c("black","red","blue"))
y4=dnorm(theta,0,1)
y5=dnorm(theta,0,2)
y6=dnorm(theta,0,3)
plot(theta,y4,type='l',ylab='Density',xlab=expression(pi))
lines(theta,y5,type="l",col="red")
lines(theta,y6,type="l",col="blue")
